logging.level:
  root: INFO
  com.shansown.aliexpress: DEBUG
com.shansown.aliexpress:
    ali-access:
      api-key: 28110
      tracking-id: shansown
      call-frequency: 100000
      signature: KjEWugZwudL
