spring:
  application.name: reseller
  cache:
    cache-names: categories
    caffeine:
      spec: expireAfterWrite=1h
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari.maximum-pool-size: ${MAX_POOL_SIZE}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
com.shansown.aliexpress:
    ali-access:
      api-key: 28110
      tracking-id: shansown
      call-frequency: 100000
      signature: KjEWugZwudL
logging.level:
  root: INFO

---
spring:
  profiles: dev
logging.level:
  com.shansown.aliexpress: DEBUG